package com.mall.model;

public class AccountUserProfile extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user_profile.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user_profile.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user_profile.user_profile_id
     *
     * @mbg.generated
     */
    private Integer userProfileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user_profile.id
     *
     * @return the value of account_user_profile.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user_profile.id
     *
     * @param id the value for account_user_profile.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user_profile.account_id
     *
     * @return the value of account_user_profile.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user_profile.account_id
     *
     * @param accountId the value for account_user_profile.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user_profile.user_profile_id
     *
     * @return the value of account_user_profile.user_profile_id
     *
     * @mbg.generated
     */
    public Integer getUserProfileId() {
        return userProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user_profile.user_profile_id
     *
     * @param userProfileId the value for account_user_profile.user_profile_id
     *
     * @mbg.generated
     */
    public void setUserProfileId(Integer userProfileId) {
        this.userProfileId = userProfileId;
    }
}