package com.mall.dao;

import com.mall.model.Account;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface AccountMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    @Insert({
        "insert into account (id, account, ",
        "password, nickname, ",
        "age, state_id)",
        "values (#{id,jdbcType=INTEGER}, #{account,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{nickname,jdbcType=VARCHAR}, ",
        "#{age,jdbcType=INTEGER}, #{stateId,jdbcType=INTEGER})"
    })
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    int insertSelective(Account record);


    List<Account> queryForList();

    List<Account> getAllUser();

    Account findAccountByAccountPwd(@Param("account") String account,@Param("password") String password);

    Account findAccountByAccount(@Param("account") String account);


}