package com.mall.dao;

import com.mall.model.AccountState;
import org.apache.ibatis.annotations.Insert;

public interface AccountStateMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_state
     *
     * @mbg.generated
     */
    @Insert({
        "insert into account_state (id, state)",
        "values (#{id,jdbcType=INTEGER}, #{state,jdbcType=VARCHAR})"
    })
    int insert(AccountState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_state
     *
     * @mbg.generated
     */
    int insertSelective(AccountState record);
}