package com.mall.dao;

import com.mall.model.UserProfile;
import org.apache.ibatis.annotations.Insert;

public interface UserProfileMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated
     */
    @Insert({
        "insert into user_profile (id, type)",
        "values (#{id,jdbcType=INTEGER}, #{type,jdbcType=VARCHAR})"
    })
    int insert(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated
     */
    int insertSelective(UserProfile record);
}